### ISSUE TITLE
Simulating the earnings effect of a change in employer payroll tax

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Calculator#1557]
> I've been playing with TaxBrain on the OSPC web site and have a question about how it works. I haven't been able to find the answer on the web site, so I'm contacting you as the POC listed on the "About" page.
> 
> How does TaxBrain account for the employer portion of payroll taxes in calculating tax cuts and increases for individual taxpayers?  
> 
> For example, assume that in step 1 all deductions, exemptions, and credits (including EITC) are eliminated. A married or head of household tax return showing only $10,000 in W2 income would fall in the 10% bracket with taxes of $1,000. Now, suppose in step 2 we zero out Social Security taxes and increase the 10% tax rate to 22.4% to compensate. Whether this is results in a washout or a tax increase compared to step 1 depends on whether the employer portion of Social Security taxes was counted as part of the employee's income prior to the SS tax elimination, and whether you assume the employer contribution will be paid to the employee as additional income when the SS tax is eliminated. 
> 
> What does TaxBrain do?

**Comment by martinholmer** [comment]
A TaxBrain user asked:
> For example, assume that in step 1 all deductions, exemptions, and credits (including EITC) are eliminated. A married or head of household tax return showing only $10,000 in W2 income would fall in the 10% bracket with taxes of $1,000. Now, suppose in step 2 we zero out Social Security taxes and increase the 10% tax rate to 22.4% to compensate. Whether this is results in a washout or a tax increase compared to step 1 depends on whether the employer portion of Social Security taxes was counted as part of the employee's income prior to the SS tax elimination, and whether you assume the employer contribution will be paid to the employee as additional income when the SS tax is eliminated.
>
> What does TaxBrain do?

In answering this question, I'm going to follow the lead of the TaxBrain user who asked the question and ignore the Medicare (HI) payroll tax.

Here is what Tax-Calculator and TaxBrain do:

| AFTER | earnings | AGI         |  inctax | paytax |  alltax | expanded income |
| :---      | ---:         |   ---:        |       --: |     ---: |       ---: |                           ---: |
| step 1 |   10,000 |   10,000 |  1000 |    1240 |  2240 |                    10,620  |
| step 2 |  10,000  |   10,000 | 2240 |           0 |  2240 |                    10,000 |

Note that all the TaxBrain distributional results are created using pre-reform expanded income or AGI.

**Comment by martinholmer** [comment]
@MattHJensen,  What's the status of Tax-Calculator issue #1557?
Is there any reason to leave it open?

**Comment by MattHJensen** [comment]
I reported back the the requester and am waiting for a response. I am also still stewing on whether to suggest that we add some behavioral feedback to allow wages to change with the payroll tax. I'd like to leave it open a little longer.

**Comment by martinholmer** [comment]
@MattHJensen said two weeks ago:
> I reported back the the requester and am waiting for a response. I am also still stewing on whether to suggest that we add some behavioral feedback to allow wages to change with the payroll tax. I'd like to leave it open a little longer.

So, what's up with this (#1557) issue?
Have you heard back from the requestor?
Have you reached a conclusion about how to handle the hardwired assumption of complete employer payroll tax shifting?

On the latter topic, it seems odd that this shifting assumption is hardwired in Tax-Calculator when all of the rest of the analytical assumptions are parameterized.  Why is it that way?

**Comment by martinholmer** [comment]
@MattHJensen said in issue #1557:
>  I am also still stewing on whether to suggest that we add some behavioral feedback to allow wages to change with the payroll tax.

Anybody considering this issue should probably read this paper in full.
Here is a link to the paper's abstract:  https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3061657

I don't have free access to NBER working papers, so I haven't been able to read the paper.

**Comment by siervicul** [comment]
I'm the user who emailed Mr. Jensen this question, but somehow lost his follow-up email to me in my inbox (so my apologies for my failure to reply to him), but have since noticed the GitHub link from the TaxBrain site. Reading @martinholmer's explanation, I've been trying to think of what practical difference the shifting assumption would make.  TaxBrain doesn't report effective tax rate or percent change in after-tax income, but those could be significantly affected by how the employer portion of payroll taxes is treated.  For example, my scenario above shows no net tax cut or increase, but results in a decrease in after-tax income and an increase in effective tax rate.  On different assumptions, the after-tax income and effective rate would be unchanged if the tax amount is unchanged.

I think it would be useful to allow the user to separately adjust the employer-side and employee-side payroll tax rates.  This would allow one to accurately model a repeat of the 2011-2012 "payroll tax holiday," which decreased the employee portion of Social Security taxes from 6.2% to 4.2% (while leaving the employer side unchanged).  

Also (and especially if TaxBrain is updated to report effective tax rates and/or changes to after-tax income), I think it would be useful to allow the user to specify the proportion of employer-side payroll tax cuts that are passed on to the employee.  This would be important for modeling reforms involving integration of payroll and income tax.

I have access to the paper that @martinholmer linked and have read it.  It discusses a reform in Sweden that cut payroll taxes only on younger employees, which resulted in some of the tax cut being passed on through higher wages, but spread out among all workers rather than limited to the younger employees whose payroll taxes were directly affected.  The paper concludes that while equity concerns likely prevented firms from increasing the wages only of younger employees and not of older employees, the targeted tax cut made younger employees relatively less expensive and therefore increased hiring of younger employees by some firms was observed.  

To me, the implication of the paper is that a broad-based (rather than targeted) employer-side payroll tax cut would be more likely to be passed on directly to employees in the form of higher wages, while a more narrowly-targeted cut is less likely to affect wages (because it's impractical for employers to pay differential wages to the targeted group of employees) and more likely to incentivize hiring of the targeted group (which was actually the intent of the Swedish cut, aimed at increasing the employment rate of younger people).  Furthermore, it's conceivable that a reform integrating payroll and income taxes could be structured to _require_ employers to increase wages by the amount of the eliminated employer-side taxes.

**Comment by martinholmer** [comment]
Thank you, @siervicul, for your [December comment](https://github.com/open-source-economics/Tax-Calculator/issues/1557#issuecomment-352026213) to issue #1557.  Sorry, it has taken us so long to respond, but we've been busy enhancing Tax-Calculator to support analysis of TCJA and now making TCJA current-law policy.  Hopefully in the next few months, we will be able to focus more attention on the issues you raise.

For now, let me be sure that we understand the nature of your Tax-Calculator enhancement requests.  You seem to be asking for two (closely related) enhancements:

1. Separate employee and employer payroll tax rates (for OASDI and for HI).

2. Add ability to simulate employer wage-paying behavior when employer payroll tax liabilities change.

Is that an accurate description of the enhancements you're requesting?

My personal view is that these enhancements are desirable and ought to be added to Tax-Calculator.
But we have other pressing issues, so I don't really know what kind of a time table to give you.

Can you suggest the name of a behavioral parameter and its logic (in words) that could be used in item 2?
Right now, there is no employer wage-paying response, so the implicit value of this new parameter is currently hard-coded to zero.  If we add this behavior to Tax-Calculator, you could think of that enhancement as simply allowing nonzero values for the parameter.  What would be the valid range of parameter values?  How would the value of the parameter affect an employee's wage/salary income?

Even if you can't contribute Python code, it would be extremely useful (and speed things up) if you can clarify the logic of the enhancement in words or in algebra.  No need to focus on the enhancement in item 1 because that is clear.

**Comment by martinholmer** [comment]
In issue #1557, @siervicul said:
> Also (and especially if TaxBrain is updated to report effective tax rates and/or changes to after-tax income), I think it would be useful to allow the user to specify the proportion of employer-side payroll tax cuts that are passed on to the employee.

If you're interested in marginal tax rates and expanded income and after-tax expanded income, you might want to consider using the Tax-Calculator command-line tool, `tc`, which gives you those variables (and many more) for each filing unit in a representative sample or in a set of filing units that you specify.   Also, you can simulate the new current-law policy: TCJA.

You don't need to do any computer programming to use `tc`, so it might be an option for you.
Read this [user documentation](http://open-source-economics.github.io/Tax-Calculator/) for more information about whether or not this approach to working with Tax-Calculator would work for you.  If you do start using `tc` and have questions after reading the user documentation, feel free to pose your questions here by raising a new issue.

**Comment by martinholmer** [comment]
@siervicul,  It has been three months since there has been any discussion of Tax-Calculator issue #1557.
Are you still interested in this issue?  If so, what is your response to [this comment](https://github.com/open-source-economics/Tax-Calculator/issues/1557#issuecomment-355639623) in the #1557 discussion?

**Comment by martinholmer** [comment]
We've heard nothing from the person who initiated this **TaxBrain** issue since December 15, 2017.
If one wanted to simulate the employer wage-paying response to a change in payroll tax parameters, this could be done in a custom Python script that uses the Tax-Calculator library.  Adding this to the Tax-Calculator library seems inappropriate given that there is no widely accepted algorithm that describes this kind of response.  Better to leave it up to the Tax-Calculator user to make their own decisions about how to characterize such an employer wage-paying response.  Given this situation, it seem sensible to close this issue.

**Comment by MattHJensen** [comment]
+1 for closure. Thanks @martinholmer

**Comment by MattHJensen** [comment]
Reopening this issue based on renewed interest from users.

**Comment by MaxGhenis** [comment]
@MattHJensen @jdebacker @nikhilwoodruff @bodiyang and I discussed this at today's Tax-Calculator meeting. We'll come back to it in more depth at our next one in two weeks. This is also relevant to openfisca-uk, as we intend to have it modeled before the employer-side National Insurance rise scheduled for April 7.
