### ISSUE TITLE
Can Tax-Calculator use a taxpayer dataset formatted for NBER TAXSIM?

### ISSUE THREAD

**Issue by evtedeschi3** [PSLmodels/Tax-Calculator#2178]
I thought I read before that it could, but I didn't see / missed mention of this in the latest official documentation. 

If so, are the required variables the same as in TAXSIM v27? E.g. https://users.nber.org/~taxsim/taxsim27/ 

Or are there any differences / additions?

**Comment by MattHJensen** [comment]
@evtedeschi3, does this file look like what you need? 

https://github.com/PSLmodels/Tax-Calculator/blob/7c39274b952328d7f36651f2d20848b9106120a2/taxcalc/validation/taxsim/taxcalc.sh

The action to translate from taxsim input to taxcalc input is happening here: https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/validation/taxsim/prepare_taxcalc_input.py. 

Look in the validation and validation/taxsim folders to see the context. @martinholmer has significantly more experience with these files (having written and used them), but he may be out on vacation at the moment.

**Comment by martinholmer** [comment]
@evtedeschi3,  sorry for my delay in responding to your question:
> Can Tax-Calculator use a taxpayer dataset formatted for NBER TAXSIM-27? 

While I was still on vacation, @MattHJensen gave a perfect answer.  I can't improve on that answer but I can provide more context.

You were absolutely correct when you said:
> I thought I read before that it could, but I didn't see / missed mention of this in the latest official documentation.

The old script that did this (which predated the `tc --dump` capability) has been replaced by the scripts in the `taxcalc/validation/taxsim` directory.  And the new scripts have been updated to handle TAXSIM-27 (rather than the old 22-input-variable version of TAXSIM).

As of the beginning of 2019, there has been considerable Tax-Calculator-versus-TAXSIM-27 validation for 2017, and much less for the years 2013-2016.  Because TAXSIM-27 is already using the actual policy parameter values for 2018 and Tax-Calculator is not (see issue #1694), we have not undertaken any comparison of output from the two models for 2018 filing units.  We plan to update Tax-Calculator to use actual 2018 values (as opposed to 2017 projected values) soon.  Once that is done we will be able to conduct a comparison for a randomly-generated sample of 2018 filing units.

All this means two things:

1. You should submit a bug report if, in your own work, you find more than a rounding-error difference between Tax-Calculator and TAXSIM-27 payroll tax liability or individual income tax liability for a 2013-2017 filing unit.

2. You should not be surprised if 2018+ output from Tax-Calculator and TAXSIM-27 differ.

**Comment by evtedeschi3** [comment]
Perfect. Thank you both!

**Comment by evtedeschi3** [comment]
OK, so I've created a file I've named `c17_taxsim.csv`. It's based on data from the 2018 CPS ASEC. It's comma-delimited and has columns for all the TAXSIM27 variables, though I have assigned zeros to ones with insufficient data in the CPS. 

Crucially, my variables aren't all in the same order as the TAXSIM27 page present them, though they do all have names / first row column headers that are the same as the TAXSIM27 named fields.

Also, I've narrowed down my file to just records with `mstat == 1 | mstat == 2`.

Here's the output when I run the script:

```
Traceback (most recent call last):
  File "prepare_taxcalc_input.py", line 114, in <module>
    sys.exit(main())
  File "prepare_taxcalc_input.py", line 57, in main
    invar = translate(ivar)
  File "prepare_taxcalc_input.py", line 76, in translate
    assert np.all(np.logical_or(mstat == 1, mstat == 2))
AssertionError
ERROR: prepare_taxcalc_input.py failed
```

**Comment by martinholmer** [comment]
@evtedeschi3 said in Tax-Calculator issue #2178:
> OK, so I've created a file I've named `c17_taxsim.csv`. It's based on data from the 2018 CPS ASEC. It's comma-delimited and has columns for all the TAXSIM27 variables, though I have assigned zeros to ones with insufficient data in the CPS.
>
> Crucially, my variables aren't all in the same order as the TAXSIM27 page present them, though they do all have names / first row column headers that are the same as the TAXSIM27 named fields.
>
> Also, I've narrowed down my file to just records with mstat == 1 | mstat == 2.
>
> Here's the output when I run the script:
>```
>Traceback (most recent call last):
>  File "prepare_taxcalc_input.py", line 114, in <module>
>    sys.exit(main())
>  File "prepare_taxcalc_input.py", line 57, in main
>    invar = translate(ivar)
>  File "prepare_taxcalc_input.py", line 76, in translate
>    assert np.all(np.logical_or(mstat == 1, mstat == 2))
>AssertionError
>ERROR: prepare_taxcalc_input.py failed
>```

The `prepare_taxcalc_input.py` script expects a file that could be uploaded to TAXSIM for processing.
My guess is that your `c17_taxsim.csv` file would generate all kinds of errors if uploaded to TAXSIM because TAXSIM does not deal with CSV-formatted files.  It expects a file with 27 **space-delimited** columns in a **specific order** as shown on the [TAXSIM homepage](https://users.nber.org/~taxsim/taxsim27/).  And it expects a file **without a header row**.

**Comment by evtedeschi3** [comment]
That's what I feared. Thank you.

**Comment by feenberg** [comment]
taxsim 27 will accept commas between items, but as Martin says, no 
variable names in the first row and the order of variables is fixed.

dan

**Comment by evtedeschi3** [comment]
Fantastic, thank you. Works now.
