### ISSUE TITLE
Questions about CTC values in policy_current_law.json

### ISSUE THREAD

**Issue by Peter-Metz** [PSLmodels/Tax-Calculator#2197]
I was hoping to receive some clarification on variables relating to the Child Tax Credit in `policy_current_law.json`, namely "_CTC_c" and "_DependentCredit_Child_c".

"_CTC_c" is "the maximum amount of credit allowed for each child" and is classified as a "Nonrefundable Credit". In `policy_current_law.json`, the pre-TCJA "_CTC_c" values are $1,000 and the 2018, post-TCJA value is $1,400. 

The description of "_DependentCredit_Child_c" is the "Nonrefundable credit for child dependents on top of the child tax credit". The 2017, pre-TCJA value is $0 and the 2018, post-TCJA value is $600.

Pre-TCJA, the maximum CTC was $1,000, all of which was non-refundable. Post-TCJA, the maximum CTC is $2,000, of which up to $1,400 is refundable and $600 is non-refundable (details [here](https://www.irs.gov/newsroom/whats-new-with-the-child-tax-credit-after-tax-reform)). 

It seems to me that the "_CTC_c" values from 2013-2017 are non-refundable while the values from 2018-2025 are refundable. If the goal is to keep refundable and non-refundable credits separate, I think we should consider re-defining "_CTC_c" and/or "_DependentCredit_Child_c" and changing the values accordingly.

cc @martinholmer @MattHJensen @andersonfrailey

**Comment by martinholmer** [comment]
@Peter-Metz,  Thanks for your [perceptive observation](https://github.com/PSLmodels/Tax-Calculator/issues/2197#issue-400405494) in Tax-Calculator issue #2197.  You may well have found something that is wrong or confusing and that needs changing.  My first question to you is have you looked at the refundable "additional child tax credit" (ACTC in the parameter naming scheme)?  If not, look at those parameters and how the non-refundable CTC (`c07220`) and the refundable ACTC (`c11070`) are calculated in the `calcfunction.py` code.  After doing that, do you think the "full child tax credit" (non-refundable plus refundable) amounts are wrong in either 2017 or 2018?   Or, is just the composition of the full CTC (that is, the split between refundable and non-refundable CTC amounts) wrong?  In this debugging, you might find it useful to compare tax results for one simple filing unit at a time (in both 2017 and 2018), in which the comparison is between what Tax-Calculator produces and what Internet TAXSIM 27 produces.  You can see how to do that sort of comparison using the tools located in the subdirectory that contains [this description](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/validation/taxsim/README.md).

When you determine exactly what's wrong and what the fix is, you need to do this in a pull request that is separate from the parameter updating PR you're preparing.

**Comment by martinholmer** [comment]
@Peter-Metz,  
Have you found any evidence that Tax-Calculator is generating incorrect 2018 child tax credit amounts?

**Comment by Peter-Metz** [comment]
@martinholmer, I had the chance to look into how the CTC is computed in `calcfunction.py` and I believe that it may be miscalculating for some tax units, tax years 2018 and beyond.

For example, consider a household with $60,000 in income and 3 children eligible for CTC. According to TAXSIM 27, under TCJA, this family should receive the full $6,000 in CTC ($3,939 deducted from liabilities and $2,061 refunded). However, with Tax-Calculator, this family would only receive $4,200. See the calculation below:

1. Calculate `dep_credit`: $600 x 3 = $1,800
2. Subtract `dep_credit` from `avail`: $3,939 - $1,800 = $2,139
3. Calculate `c07220` by taking the minimum of `prectc` ($4,200) and result from Line 2: $2,139
4. Calculate ACTC (`c11070`): $261
5. Total CTC is Line 1 + Line 3 + Line 4= $4,200

I believe the issue can be resolved by doing the following:

1. `_CTC_c`, should not be defined as "nonrefundable" or "refundable" and should instead be the maximum total amount allowed, or $2,000 in 2018
2. There should be a new variable that takes the place of `_DependentCredit_Child_c` that shows the maximum amount of the CTC that is refundable; in 2018, this amount is $1,400. `dep_credit` would now reflect the amount received from the credit for non-child dependents, which is, in fact, non-refundable
3. This new variable created in line 2 should be added to the logic of the calculation of `c11070`, since the ACTC is calculated differently under TCJA ([2005 Form 8812](https://www.irs.gov/pub/irs-prior/f8812--2005.pdf) vs. [2018 Form 8812](https://www.irs.gov/pub/irs-pdf/f1040s8.pdf))

@martinholmer, I'd greatly appreciate your review of the above. If you agree with part or all of my assessment, I would be happy to open a PR to rectify the issue.

**Comment by martinholmer** [comment]
@Peter-Metz, Thanks for [this helpful comment](https://github.com/PSLmodels/Tax-Calculator/issues/2197#issuecomment-457683776).  You are definitely correct that the CTC+ODTC and the ACTC computations for 2018+ are seriously messed up in the current version of Tax-Calculator.  Over the past few days I've been preparing some still-incomplete logic changes (excluding the needed policy parameter name changes you mention).  Please take a look at that [development branch](https://github.com/martinholmer/Tax-Calculator/tree/redo-ctc-actc) and let me know where you think it can be improved (since your own thinking is pretty far along).  I've been going slowly on these changes because whatever changes we make have to leave pre-2018 results unchanged.  That is true for the code on the tip of the development branch, but that code produces many 2018 differences when compared to TAXSIM-27.

Note that when you look at that development branch on my fork of Tax-Calculator, it will say it is one commit ahead of the master branch.  Click the Compare button on the right-hand sider of that line to see the changes in diff format.

**Comment by martinholmer** [comment]
Merging pull request #2223 was the final step in resolving the problems identified by @Peter-Metz in issue #2197.  Thank you, @Peter-Metz, for raising this issue, which I'm going to close now.
