### ISSUE TITLE
Itemized Deduction sensitive to order of removal

### ISSUE THREAD

**Issue by erinmelly** [PSLmodels/Tax-Calculator#2242]
When removing all of a person’s itemized deductions (without giving them a standard deduction), the value of each type of deduction is sensitive to the order in which they are removed. For example, we may find that a person has lost $20 of charitable deductions and $40 of interest deductions if we remove them in that order, but that he has lost $25 of charitable deductions and $35 of interest deductions if we remove the interest deductions first.  (The total appears to stay the same.) One would think that, regardless of the removal order, the value of each lost deduction would always be the value of that deduction that the person had claimed. Note that this is NOT a stacking order issue, as we are talking about the value of the deduction itself, and not the revenue generated from that itemized deduction.

First implement:
`reformA = {2018: {'_STD': [[0.0, 0.0, 0.0, 0.0, 0.0]],  '_ID_StateLocalTax_hc': [1.0],  '_ID_RealEstate_hc': [1.0], '_ID_InterestPaid_hc': [1.0], '_ID_Charity_hc': [1.0]}}`

Then implement:
`reformB = {2018: {'_STD': [[0.0, 0.0, 0.0, 0.0, 0.0]], '_ID_StateLocalTax_hc': [1.0], '_ID_RealEstate_hc': [1.0], '_ID_InterestPaid_hc': [1.0], '_ID_Charity_hc': [1.0], '_ID_Medical_hc': [1.0]}}`

Note that the only difference between A and B is the addition of the medical itemized deduction haircut. Therefore,  the difference between the weighted value of `c04470` under A versus under B should result in the total amount of medical deduction claimed in a scenario in which no one claims the standard deduction. However, this is not true. When analyzing `reformC = {2018: {'_STD': [[0.0, 0.0, 0.0, 0.0, 0.0]]}}`, the weighted total of `c17000` under reform C is not equivalent to the difference of the weighted total of `c04470` in A and B.

Furthermore, a different value for the medical deduction is computed when changing the order in which the deductions are removed. In other words, create a reform D such that `reformD = {2018: { '_STD': [[0.0, 0.0, 0.0, 0.0, 0.0]],'_ID_Medical_hc': [1.0]}}`. Like above, the difference in weighted value of `c04470` under reform C verses reform D should give you the total amount of the medical itemized deduction claimed. However, the difference in the weighted value of `c04470` between C and D is not equal to the difference in the weighted value of `c04470` between A and B which is not equal to weighted value of `c17000` under C. In theory, this should not be the case.

If the Pease limitation was in effect, it could be a question of how that limitation is allocated across the different deduction types. But this is happening in 2018 when there is no Pease limitation. Also note this happens for all itemized deductions, not just medical.

**Comment by martinholmer** [comment]
@erinmelly, thank you for your detailed bug report in Tax-Calculator issue #2242.  So far, I have focused only on your first issue, which involves a comparison of results from your reformA, reformB, and reformC.  My plan is to resolve that issue first, and then we will see where things stand on your second issue.

I have been able to replicate the puzzling results about medical expenses deducted (`c17000`) not been equal to the change in total itemized expenses with and without a complete haircut of itemized medical expenses.  It turns out that this puzzling result is caused by two different things: a misspecification of the "no standard-deduction" reform provision and a bug in Tax-Calculator.

First, the reform misspecification.  Your expectations are based on "a scenario in which no one claims the standard deduction".  But to achieve that "scenario" you need to include this in your reform:
```
        '_STD_Aged': [[0.0, 0.0, 0.0, 0.0, 0.0]],
        '_STD': [[0.0, 0.0, 0.0, 0.0, 0.0]],
```
Leaving the values of `_STD_Aged` at their positive values under current law meant that millions of filing units were actually claiming a standard deduction.

Second, fixing the first problem still produces a (smaller) puzzling result.  I believe the remaining puzzle is caused by a long-standing bug in Tax-Calculator.   Years ago, when the itemized-vs-standard-deduction logic was coded, the value of `c04470` (total itemized deductions) was adjusted to reflect the optimization decision each filing unit goes through to decide whether or not to itemize.  But that logic failed to adjust the value of `c17000` (medical expenses deducted).  And it also failed to adjust the other components of the `c04470` total.

The bug-fix plan is to add a test similar to your comparison that fails (presumably) for each component of total itemized expenses, not just medical expenses deducted.  Then I'll try to fix the bugs so that the new test passes.  If I'm successful, then we'll issue a bug-fix release, Tax-Calculator 1.0.1.

Here is my script that distills your code to show the bug.
```
from taxcalc import *
import numpy as np

reform_year = 2018

reformA = {
    reform_year: {
        '_STD_Aged': [[0.0, 0.0, 0.0, 0.0, 0.0]],
        '_STD': [[0.0, 0.0, 0.0, 0.0, 0.0]],
    }
}
polA = Policy()
polA.implement_reform(reformA)
assert not polA.parameter_errors

reformB = {
    reform_year: {
        '_STD_Aged': [[0.0, 0.0, 0.0, 0.0, 0.0]],
        '_STD': [[0.0, 0.0, 0.0, 0.0, 0.0]],
        '_ID_Medical_hc': [1.0]
    }
}
polB = Policy()
polB.implement_reform(reformB)
assert not polB.parameter_errors

recs = Records()  # using puf.csv as input data

calcA = Calculator(policy=polA, records=recs, verbose=False)
calcA.advance_to_year(reform_year)
calcA.calc_all()
calcB = Calculator(policy=polB, records=recs, verbose=False)
calcB.advance_to_year(reform_year)
calcB.calc_all()

"""
EXPECTATION:
"Note that the only difference between A and B is the addition of the
medical itemized deduction haircut. Therefore, the difference between
the weighted value of `c04470` under A versus under B should result in
the total amount of medical deduction claimed in a scenario in which
no one claims the standard deduction. However, this is not true. When
analyzing `reformC = {2018: {'_STD': [[0.0, 0.0, 0.0, 0.0, 0.0]]}}`,
the weighted total of `c17000` under reform C is not equivalent to the
difference of the weighted total of `c04470` in A and B."
"""

# c00470 is total itemized deductions (zero for non-itemizers)
c04470A = calcA.weighted_total('c04470') * 1e-9
numstdA = calcA.array('s006').where(
            calcA.array('standard') > 0., 0.).sum() * 1e-6
assert np.allclose(numstdA, 0.)  # will fail without setting _STD_Aged to zero
c04470B = calcB.weighted_total('c04470') * 1e-9
numstdB = calcB.array('s006').where(
            calcB.array('standard') > 0., 0.).sum() * 1e-6
assert np.allclose(numstdB, 0.)  # will fail without setting _STD_Aged to zero
# c17000 is medical expenses deducted
c17000A = calcA.weighted_total('c17000') * 1e-9

print('c04470A= {:.3f}'.format(c04470A))
print('numstdA= {:.3f}'.format(numstdA))
print('c04470B= {:.3f}'.format(c04470B))
print('numstdB= {:.3f}'.format(numstdB))
print('c17000A= {:.3f}'.format(c17000A))

if np.allclose(c04470A - c04470B, c17000A):
    print('EXPECTATIONS are confirmed')
else:
    print('EXPECTATIONS not confirmed')
    print('c00470A-c00470B={:.3f} != c17000A={:.3f}'.format(
        c04470A - c04470B, c17000A
        )
    )
```
And here is what `python i-2242.py` produces:
```
c04470A= 1368.804
numstdA= 0.000
c04470B= 1237.732
numstdB= 0.000
c17000A= 135.537
EXPECTATIONS not confirmed
c00470A-c00470B=131.072 != c17000A=135.537
```
Thanks again for the bug report.  Normally, I would expect to resolve this in a day or so, but I'm going to be out of the office on Sunday, Monday, and Tuesday, traveling to and from DC for the PSL Meetup on Monday.

**Comment by martinholmer** [comment]
@erinmelly, Tax-Calculator release 1.0.1 is now available.  Can you confirm that your itemized deduction calculations make more sense now?  If not, please raise another issue that describes how you got the result that doesn't make sense.  Thanks again for the bug report in issue #2242.

**Comment by erinmelly** [comment]
@martinholmer After updating to Tax-Calculator 1.0.1, the itemized deductions are now equivalent in the way we would expect. Also, thanks for pointing out the need to include `'_STD_Aged'` in those reforms. Thanks for the fix!

**Comment by martinholmer** [comment]
@erinmelly said in Tax-Calculator issue #2242:
> After updating to Tax-Calculator 1.0.1, the itemized deductions are now equivalent in the way we would expect. Also, thanks for pointing out the need to include `'_STD_Aged'` in those reforms. Thanks for the fix!

Sure.  You're developing into one of our more sophisticated users,  so whenever you see Tax-Calculator results that look suspicious raise an issue describing exactly how you generated the results and why you think they are suspicious.  That would be a big help in improving the quality of Tax-Calculator.
