### ISSUE TITLE
Adding parameters to analyze payroll tax exemption

### ISSUE THREAD

**Issue by Peter-Metz** [PSLmodels/Tax-Calculator#2362]
One of @MattHJensen's contacts requested revenue estimates for the following reforms:

>Exempting the first $XXX of labor income from the employee side of the OASDI payroll tax and exempting the first $XXX in labor income from both sides of the OASDI payroll tax

In a [branch](https://github.com/Peter-Metz/Tax-Calculator/tree/ptax_em), I modeled these reforms both by augmenting the code base (`calcfunctions.py`) and by modifying the recipe for analyzing a non-parametric reform (`reform06.py`). The changes to the code base and the modified recipe 06 can be found in this [diff](https://github.com/Peter-Metz/Tax-Calculator/pull/1/files).

I've added two parameters: `FICA_ss_em`, the exemption amount, and `FICA_ss_em_employer`, a boolean that indicates whether the exemption will be applied to both the employer and the employee portions of the FICA rate. The recipe06 effectively recreates the function to calculate `ptax_oasdi` while incorporating the new parameters to implement an exemption. 

@MattHJensen, would you please review my changes to make sure they conform to your understanding of what the user is looking for and that my implementation is appropriate?

**Comment by MattHJensen** [comment]
@Peter-Metz, thanks a great deal for your work on this. 

Do you need the new _em variables in lines 102-121 of `calcfunctions.py`? The code may be cleaner if you modified the original variables to work no matter the exemption values (including the 0s under current law.)

If there are other areas in `calcfunctions.py` that are similar in style to what you are suggesting, or if there are other reasons why you think the new variables might be helpful, please mention anything that would advance our discussion.

**Comment by Peter-Metz** [comment]
@MattHJensen said:

>Do you need the new _em variables in lines 102-121 of calcfunctions.py?

I think we need these new variables to be able to model a scenario where there is an exemption for the employee portion of FICA but not the employer portion. In this scenario, the employee portion and the employer portion are based on different taxable incomes. I agree that if we remove the option to specify this type of reform (i.e. the new parameter `FICA_ss_em_employer`), we could get rid of these `_em` variables. Is this consistent with your understanding of the reform?

**Comment by MattHJensen** [comment]
@Peter-Metz, using your branch, would you mind posting revenue and distributional tables for these two reforms

- $5000 exemption to employee side only. 
- $2,500 exemption to both employee and employer side. 

I don't think there should be any significant difference, but I may be missing something. If I'm right, then I'll just tell the requestor to approximate his answer by halving the combined exemption amount.

**Comment by Peter-Metz** [comment]
@MattHJensen, see below for a distributional table and a revenue table. `reform1` is the $5000 exemption to employee side only and `reform2` is the $2,500 exemption to both employee and employer side. As expected, the two reforms have similar effects.

![Screen Shot 2019-07-30 at 1 34 04 PM](https://user-images.githubusercontent.com/43755005/62151648-ce8f0f80-b2ce-11e9-9d90-126bd1dac755.png)

![Screen Shot 2019-07-30 at 1 34 12 PM](https://user-images.githubusercontent.com/43755005/62151653-d2229680-b2ce-11e9-8649-4d84d687f10f.png)

**Comment by MattHJensen** [comment]
Cool. What do you think about revising the code to only facilitate exemptions that are applied to both sides of the tax, and then adding a note explaining that an exemption to only the employer or employee sides can be approximated by halving the value of the exemption?

**Comment by Peter-Metz** [comment]
Sure thing. Should I open a PR or hold off for now?

**Comment by MattHJensen** [comment]
How about  update your fork first and then we can decide how to proceed.

**Comment by Peter-Metz** [comment]
@MattHJensen check out the new [diff](https://github.com/Peter-Metz/Tax-Calculator/pull/1/files) for `calcfunctions.py`. Overall, much simpler, but notice that I added new intermediate variables with an `_mc` suffix because the exemption does not apply to the medicare tax.

**Comment by MattHJensen** [comment]
Thanks @peter-metz. 

@martinholmer, do you have any questions or comments about this issue before I ask @Peter-Metz to open a PR? I figure we can continue discussing aspects of the implementation in the PR, but this issue has been helpful for thinking about what it is we are trying to implement and the complexities associated with different options.  

@Peter-Metz, while Martin takes a look at this, could you add a reform using the new parameter to `tests/reforms.json` on your branch? That will be needed for your PR. You will have to modify at least a couple of files -- test errors will guide you.

**Comment by martinholmer** [comment]
@Peter-Metz said in Tax-Calculator issue #2362:
> One of @MattHJensen's contacts requested revenue estimates for the following reforms:
>> Exempting the first $XXX of labor income from the employee side of the OASDI payroll tax and exempting the first $XXX in labor income from both sides of the OASDI payroll tax

What exactly is the requestor's policy objective?   Why add an exemption to FICA and SECA?

**Comment by MattHJensen** [comment]
> What exactly is the requestor's policy objective? Why add an exemption to FICA and SECA?

I'm not sure and don't feel it is my position to ask about it in this situation. But, for what it's worth, In my experience there are usually both political and policy objectives that might encourage someone to want to see the effects of a reform. Also, sometimes people wish to see the effect of a reform without necessarily wanting to advocate for that reform.

**Comment by martinholmer** [comment]
@MattHJensen, The problem with a payroll tax exemption is that it is difficult to make it work correctly with all the variants of the payroll tax that we allow with the current set of payroll tax policy parameters.   The work in issue #2362 does not meet that standard.

Why doesn't the requestor use the `tc --dump` output to get an estimate of the revenue effects, in the same way that @ernietedeschi did to estimate the effects of a refundable child/dependent care expense credit?

**Comment by MattHJensen** [comment]
> Why doesn't the requestor use the tc --dump output to get an estimate of the revenue effects, in the same way that @ernietedeschi did to estimate the effects of a refundable child/dependent care expense credit?

This user is not that technologically sophisticated. This goal is to pair this with other provisions in Tax-Brain simulations. 

> The problem with a payroll tax exemption is that it is difficult to make it work correctly with all the variants of the payroll tax that we allow with the current set of payroll tax policy parameters.

Could you tell us the problem that you see -- a high level overview is fine if you have limited time --  and then @Peter-Metz and I can think about potential solutions?

**Comment by martinholmer** [comment]
@MattHJensen said:
> This user is not that technologically sophisticated. Their goal is to pair this with other provisions in Tax-Brain simulations.

So, there **is** a policy objective because this provision is being paired with other reform provisions.

Why would anybody propose a reform that gave the same dollar tax rebate to a poor person with a few thousand dollars of earnings as to a rich person with millions of dollars of earnings?  If I were the requestor, I'd be worried about the critical response I'd get from proposing such a reform.  But I'm not the requestor; I'm a maintainer of Tax-Calculator.  In that role I see a big maintenance burden and substantial reputation risk  to Tax-Calculator and PSL if we implement such a reform capability.

**Comment by MattHJensen** [comment]
> In that role I see a big maintenance burden and substantial reputation risk to Tax-Calculator and PSL if we implement such a reform capability.

@martinholmer, could you please expand on your concerns?

**Comment by martinholmer** [comment]
I would like Tax-Calculator to have the capability of rebating to low-income people some or all of their payroll tax liability.  But I think that the approach being taken in issue #2362 is an inefficient and complex way to do that.  So complex that the proposed code in #2362 has a number of problems.  There is a much simpler way to provide users with this new capability.

Some background on the earned income tax credit (EITC) will be useful for understanding the simpler approach.  One of the main original goals of the EITC was to offset the payroll taxes paid by poor people.  Over the decades the credit has become more generous, so that it rebates more than the payroll tax liability for families with kids.  However, even to this day, low-earning filing units with no kids get a credit that is exactly equal to the employee share of payroll tax liability.  For the zero-kids group, the credit rate (`EITC_rt`) is 0.0765 (which is the employee payroll rate for OASDI+HI) and the maximum refundable credit (`EITC_c`) is $519 in 2018, which is equivalent to an employee-share OASDI+HI exemption of about $6784.  Of course, this maximum credit of $519 is eventually clawed back (until it drops to zero) as earnings rise beyond $6784.

The request that generated issue #2362 does not include a clawback, but my guess is that once the no-clawback capability is added to Tax-Calculator, the requestor will see how inefficient it is to give rich people the payroll tax rebates, and the requestor will be back asking for a clawback capability.  Adding such a clawback capability will be far easier in the simple approach described below.

The request at hand can be viewed as a refundable personal (as opposed to a filing unit) earned income credit, or `PEIC`, for short.  The simple approach involves adding a new calcfunction called `PersonalEIC` that uses two new income tax policy parameters --- `PEIC_c`, the maximum PEIC amount, and `PEIC_rt`, the crediting rate --- to compute the refundable PEIC amount for the taxpayer and for the spouse (if present).  The default values of `PEIC_c` and `PEIC_rt` would be zero.  Notice that this approach provides the ability to simulate a much wider range of reforms than does the exemption approach.  And it also dramatically simplifies the calculations, improving code readability and reducing the chance of bugs.  And if the capability of clawing back the `PEIC_c` amount from higher-income filing units is ever requested, the logic (which would probably follow the current-law EITC) would be far easier to implement than if the payroll tax exemption approach is adopted.

**Comment by MattHJensen** [comment]
@martinholmer, thanks very much for this information and suggestion. I spoke with the user this morning and he is happy with the PEIC option. @Peter-Metz, what do you think?

**Comment by Peter-Metz** [comment]
Thanks for the background @martinholmer. I'd be happy to help implement a function that calculates the proposed `PEIC` in the coming weeks (I'll be on vacation next week). For educational purposes, @martinholmer, do you have some time tomorrow to hop on the phone to privately discuss the problems in my current implementation of the exemption so I do not repeat them?

**Comment by martinholmer** [comment]
@Peter-Metz asked:
> For educational purposes, @martinholmer, do you have some time tomorrow to hop on the phone to privately discuss the problems in my current implementation of the exemption so I do not repeat them?

Sure.  Should I call you at 10:00 on Friday?

**Comment by Peter-Metz** [comment]
@martinholmer, that would be great. 202-862-5891

**Comment by martinholmer** [comment]
@Peter-Metz,  OK.  Talk with you then.

**Comment by martinholmer** [comment]
@Peter-Metz said in issue #2362:
> I'd be happy to help implement a function that calculates the proposed PEIC in the coming weeks (I'll be on vacation next week).

How about splitting the work in order to make the new capability available sooner?
I can do the basic work now and include it in a release early next week (which is also fixing a bug).
Then, after you're back from vacation, you can add the PEIC clawback (or phase-out) parameters and associated logic.

I'm going to open a pull request that implements the no-clawback PEIC before our phone call.  
It would be very helpful if you could look at it today to provide a review before you leave on vacation.

**Comment by Peter-Metz** [comment]
@martinholmer, that sounds great. Thanks for opening the PR.

**Comment by MaxGhenis** [comment]
@MattHJensen Just curious, did this request concern the Medicare for All financing? The Sanders bill exempts incomes below $29,000 for a family of four, while the Harris bill exempts $100,000.

**Comment by MattHJensen** [comment]
> did this request concern Medicare for All financing? The Sanders bill exempts incomes below $29,000 for a family of four, while the Harris bill exempts $100,000.

@MaxGhenis, I haven't asked. When I have an opportunity, I'll let you know.

**Comment by martinholmer** [comment]
Issue @2362 has been resolved by the merge of pull request #2364.
