### ISSUE TITLE
Handling of UBI

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2415]
Currently, UBI is handled in Tax-Calculator as a spending program and therefore has no direct effect on tax liabilities.  

Since it seems likely that if the US were to adopt a UBI, it would likely be administered through the tax system as a refundable credit (we love our tax expenditures!), would it be possible to incorporate UBI into TC as a refundable credit?  Perhaps a flag to switch the UBI from being a spending program to a tax program?

@MaxGhenis thoughts on this?

**Comment by MaxGhenis** [comment]
It would be cool to have a negative income tax feature in taxcalc, but UBI itself seems more comparable to Social Security benefits, or other benefits like SSI and SNAP. Does OG-USA have its own logic for Social Security benefits? And other benefits aren't in yet, right? Would they also be modeled as negative taxes?

**Comment by jdebacker** [comment]
@MaxGhenis OG-USA does have it's own logic for SS benefits.  And you are right, it does not allow one to model change in other benefits programs like SNAP.  

In the long-term, I think it'd be ideal to have a microsimulation model of benefits programs and then use such a model, jointing with Tax-Calculator, to estimate net tax/transfer functions of ETRs and MTRs.  But that's a ways off.

My suggestion in this issue is that it would be helpful, at the very least for budgeting purposes, to be able to model a UBI as a refundable credit since that is, in my view, a very likely way in which such a program would be administered.  OG-USA will be able to incorporate UBI from Tax-Calculator either way (as a spending or tax program).

**Comment by MaxGhenis** [comment]
Gotcha. I agree there's a good chance that a UBI would be administered as a refundable tax credit, e.g. the American Family Act pseudo-child-allowance is really a monthly tax credit. But I think it's possible that it would be administered separately; e.g., carbon dividend bills in Congress are monthly checks outside of the tax code. taxcalc's current option for UBI to be taxed as personal income also differs from refundable tax credits.

In terms of taxcalc outputs, this may be personal taste but I don't find the tax rate changes as helpful as % change to after-tax income, especially when modifying benefits, where some analysts treat benefits as negative taxes. So since I'll mostly use that % change to after-tax income measure, either way would be fine for me from a usability perspective. All else equal, I think retaining the option for it to be a spending program would be useful for those who think of it that way.

**Comment by jdebacker** [comment]
Follow up questions related to Tax-Calculator's handing of UBI.  If UBI is currently handled as a spending program, why is the UBI amount not in the `benefit_cost_total` parameter computed [here](https://github.com/PSLmodels/Tax-Calculator/blob/cbaee0355dc600cc02a551de858eb05a95755987/taxcalc/calcfunctions.py#L56)?

I feel like it ought to be in `benefit_cost_total` and `benefit_value_total`.  Am I wrong?

**Comment by jdebacker** [comment]
UBI amounts are now included in benefits totals.
