### ISSUE TITLE
[Question] How does the round trip test work?

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Tax-Calculator#2542]
I'm trying to understand the [`test_round_trip_tcja_reform`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/tests/test_reforms.py#L75-L132) test:

https://github.com/PSLmodels/Tax-Calculator/blob/9c8be5552676bddca464914f3b83eac4e70299bb/taxcalc/tests/test_reforms.py#L93-L104

My understanding is that it:
1. implements `2017_law.json`
2. implements `TCJA.json`
3. checks that the parameters are back to current law (i.e. equal to `policy_current_law.json`)

My question is: Why are some parameters changed in `2017_law.json`, but not in `TCJA.json`? For example, [`EITC_ps_MarriedJ`](https://github.com/PSLmodels/Tax-Calculator/blob/9c8be5552676bddca464914f3b83eac4e70299bb/taxcalc/policy_current_law.json#L14431) is changed in [`2017_law.json`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/2017_law.json#L114), but `EITC_ps_MarriedJ` is not included in [`TCJA.json`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/TCJA.json). So, how it could it get back to its current law value if the value is updated via the `2017_law.json` file but isn't changed again by the `TCJA.json` file? 

There are a couple other parameters like this such as [`II_em_ps`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/2017_law.json#L86) and [`EITC_c`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/2017_law.json#L112).

There's a hack in the parameters code that exists specifically to get this one test to pass and I'm trying to figure out if I can remove it:
https://github.com/PSLmodels/Tax-Calculator/blob/9c8be5552676bddca464914f3b83eac4e70299bb/taxcalc/parameters.py#L314-L324

**Comment by Peter-Metz** [comment]
The way I've thought about this test is that `2017_law.json` is current law as of 2017 while `TCJA.json` is a reform using `2017_law.json` as the baseline. So, if a policy parameter appears in `2017_law.json` but not `TCJA.json`, this should mean that the parameter was not changed by TCJA.

For your three parameter examples, `EITC_ps_MarriedJ` and `EITC_c` were not changed by TCJA, so we don't expect them to be in `TCJA.json`. On the other hand, `II_em_ps` (personal exemption phaseout) was changed by TCJA and I think should belong in `TCJA.json`. Results aren't actually affected by this omission because `II_em` (personal exemption amount) is set to zero in `TCJA.json`.

As for the code snippet in `parameters.py`, I wrote that as part of the transition from `CPI_offset` to `parameter_indexing_CPI_offset`. I think that particular snippet deletes the parameter values that need to be re-indexed.

Hope that helps.

**Comment by hdoupe** [comment]
Thanks for the reply @Peter-Metz.

> As for the code snippet in `parameters.py`, I wrote that as part of the transition from `CPI_offset` to `parameter_indexing_CPI_offset`. I think that particular snippet deletes the parameter values that need to be re-indexed.

Wait, I was referring to the use of the `_init_vals` dict. Your code is fine! I'm trashing my own code!

> The way I've thought about this test is that 2017_law.json is current law as of 2017 while TCJA.json is a reform using 2017_law.json as the baseline. So, if a policy parameter appears in 2017_law.json but not TCJA.json, this should mean that the parameter was not changed by TCJA.

Ok, this makes sense to me. I think I'm remembering you telling me this in the past. I'm still hung up on this:

> So, how could it (e.g. `EITC_ps_MarriedJ`) could it get back to its current law value if the value is updated via the `2017_law.json` file but isn't changed again by the `TCJA.json` file? 

This makes me think that the test should only check parameter values that are in the `TCJA.json` file. @Peter-Metz is that reasonable or no? 

I also didn't write this test so I'm a little hesitant to update it. My main motivation is to remove the update logic that re-instates the current law parameters prior to `last_known_year` every time the `parameter_indexing_CPI_offset` is changed. I would think that it should be sufficient to just remove the parameters after `last_known_year`....

https://github.com/PSLmodels/Tax-Calculator/blob/9c8be5552676bddca464914f3b83eac4e70299bb/taxcalc/parameters.py#L370-L391

**Comment by jdebacker** [comment]
@hdoupe Can this issue be closed?

**Comment by hdoupe** [comment]
@jdebacker I'm still pretty confused about this test, but happy to re-open the issue or discuss elsewhere when I come back around to it.

**Comment by jdebacker** [comment]
My understanding of this test is similar to what Peter's saying:  It tests that if you revert to 2017 law, then layer on each change since 2017, you should get back to the current, current law baseline.

But I do not understand the snipped in `parameters.py` that @hdoupe cites.  That code should be better documented and hacks to pass tests should be removed from the codebase.

@hdoupe writes:

>  I'm still hung up on this:
> >So, how could it (e.g. EITC_ps_MarriedJ) could it get back to its current law value if the value is updated via the 2017_law.json file but isn't changed again by the TCJA.json file?

I need help understanding this.  Is this an issue with indexed parameters generally (whose indexing changed with the TCJA)?

**Comment by jdebacker** [comment]
@hdoupe I think the parameters that are not changed in `TCJA.json` and are changed in 2017_law.json` are parameters that were updated sometime before the TCJA reform and so were in the current law baseline in 2017, but were omitted in the `2017_law.json` file.

E.g.,
* The `2017_law.json` specifies `"EITC_ps_MarriedJ": {"2017": [5600, 5600, 5600, 5600]}` and the `TCJA.json` does not change this value.  But the current values of 5590 (in `policy_current_law.json` [here](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json#L15520-L15539)) were set in in PR #2240, which was after both the `2017_law.json` and `TCJA.json` files were originally created.
