### ISSUE TITLE
Child Tax Credit bonus for children under 6 years old

### ISSUE THREAD

**Issue by JackLandry** [PSLmodels/Tax-Calculator#2608]
The Child Tax Credit gives an additional [$600 for children under 6](https://www.taxpolicycenter.org/briefing-book/what-child-tax-credit) that doesn't seem to be implemented in [policy_current_law.json](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json). Should that be added, or am I missing something?

**Comment by jdebacker** [comment]
@JackLandry Thanks for looking into this.  

The CTC changes that occurred through the ARPA required the creating of new CTC parameters that allowed one to model the system under ARPA and the system before (and after) the ARPA changes.  Thus, the place to look is at the `CTC_new_` parameters.

[`CTC_new_c_under6_bonus` is set to a non-zero value](https://github.com/PSLmodels/Tax-Calculator/blob/297931b7c3cb5d7af5859ac7e6d54b3f255ddaa9/taxcalc/policy_current_law.json#L16164), but looking at this, it does appear to be incorrect.  It has a value of $1,000 instead of $600, as was specified in the [APRA.json](https://github.com/PSLmodels/examples/blob/main/psl_examples/taxcalc/ARPA.json) file and [in a unit test](https://github.com/PSLmodels/Tax-Calculator/blob/297931b7c3cb5d7af5859ac7e6d54b3f255ddaa9/taxcalc/tests/test_reforms.py#L130).

**Comment by Thirdhuman** [comment]
If I do 2 dry runs and take the difference, one with "CTC_new_c_under6_bonus" set to $0 and the other with it set to $600, I get no difference between them.

**Comment by jdebacker** [comment]
@Thirdhuman Thanks for checking this.  So that I can confirm, can I get some details:

* Are you using Tax-Calculator 3.2.0?
* What does your "reform" JSON (or dictionary) look like?
* What year(s) are you looking at?

**Comment by Thirdhuman** [comment]
Is there a way to check confirm the version that's being used via the command line?  
It should the most recent one, unless I've somehow got 2 versions on my computer and am calling the wrong one.

![Screen Shot 2021-07-26 at 5 15 13 PM](https://user-images.githubusercontent.com/20157774/127060282-4090b4d9-5ad9-4a01-9791-f4980dbe571c.png)

![Test](https://user-images.githubusercontent.com/20157774/127059834-d3221c02-6775-470f-a557-e3a87be6d637.png)

**Comment by Thirdhuman** [comment]
Is there a way to check confirm the version that's being used via the command line?
It should the most recent one, unless I've somehow got 2 versions on my computer and am calling the wrong one.

JSON structure (I've tried "CTC_new_for_all")
![Screen Shot 2021-07-26 at 5 11 11 PM](https://user-images.githubusercontent.com/20157774/127060441-c99d2369-f1c8-4e20-9a9b-0b4a329886f1.png)

Command line:
![Screen Shot 2021-07-26 at 5 15 13 PM](https://user-images.githubusercontent.com/20157774/127060511-b25d3632-80ce-4fba-933b-0d21d3f6c6d9.png)

**Comment by jdebacker** [comment]
@Thirdhuman Yes, to check your version to Tax-Calculator from the command line, type `conda list taxcalc`.

Also, note that the `CTC_new_` parameters only take on non-zero values for 2021 under the current law baseline, since that's the year the tax liability hits.

**Comment by Thirdhuman** [comment]
> @Thirdhuman Yes, to check your version to Tax-Calculator from the command line, type `conda list taxcalc`.
Yeah, it's V3.2.  
> Also, note that the `CTC_new_` parameters only take on non-zero values for 2021 under the current law baseline, since that's the year the tax liability hits.
Yeah, basically what you're saying is the old the "new_ctc" parameter is now the current law.

**Comment by jdebacker** [comment]
Fixe via PR #2609.
