### ISSUE TITLE
Issues with `write_decile_table()`

### ISSUE THREAD

**Issue by awunderground** [PSLmodels/Tax-Calculator#2795]
I am trying to use `write_tables_file()` to output distributional tables. `write_tables_file()` calls the method `write_decile_table()`, which uses the function `unweighted_sum()`. 

[This code](https://github.com/PSLmodels/Tax-Calculator/blob/150becc9c1d31e69c14a14e219e1e415df6914dd/taxcalc/taxcalcio.py#L619) includes the argument `include_groups=False` even though `include_groups` doesn't appear to be an argument for `unweighted_sum()` [source code](https://github.com/PSLmodels/Tax-Calculator/blob/150becc9c1d31e69c14a14e219e1e415df6914dd/taxcalc/utils.py#L136).

I get the following error, which is fatal:

```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
  TypeError: unweighted_sum() got an unexpected keyword argument 'include_groups'
```

**Comment by jdebacker** [comment]
@awunderground Thanks for raising this issue.  To help diagnose it, can you provide some code to replicate the error you are finding?

**Comment by jdebacker** [comment]
Further investigation showed that this bug is a result of the user having `pandas` with version < 2.2 installed in their environment.  The [`taxcalc-dev` environment](https://github.com/PSLmodels/Tax-Calculator/blob/master/environment.yml) specifies that the model requires `pandas >= 2.2`.

The specific `pandas` deprecation re the `include_groups` kwarg is noted in [this Stack Overflow thread](https://stackoverflow.com/questions/77969964/deprecation-warning-with-groupby-apply).
